### ISSUE TITLE
Feature request: Docker API via TCP

### ISSUE THREAD

**Issue by sammcj** [capnspacehook/whalewall#133]
Howdy, nice project!

Have you got any thoughts on defaulting to use something such as https://github.com/Tecnativa/docker-socket-proxy to further secure access to the docker daemon?

I use it with Traefik and have found it really reliable.

I think all that would be required is allowing access to the Docker via TCP rather than a unix socket, then you could do something like:

```yaml
networks:
  docker-proxynet: # Used for securely exposing docker.sock
    driver: bridge
    name: docker-proxynet
    internal: true
    enable_ipv6: false

services:
  dockerproxy: # see https://github.com/Tecnativa/docker-socket-proxy
    environment:
      - CONTAINERS=1
      - NETWORKS=1 (maybe?)
    container_name: dockerproxy
    image: ghcr.io/tecnativa/docker-socket-proxy:edge
    cpus: 0.75
    hostname: dockerproxy
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
    networks:
      - docker-proxynet # use only internal network
    ports:
      - 127.0.0.1:2375:2375

  whalewall:
    cap_add: 
      - NET_ADMIN
    image: ghcr.io/capnspacehook/whalewall
    network_mode: host
    volumes:
      - whalewall_data:/data
    environment:
      - DOCKER_API: tcp://dockerproxy:2375

volumes:
  whalewall_data:
```
