### ISSUE TITLE
field ips not found in type whalewall.externalRules

### ISSUE THREAD

**Issue by krokyze** [capnspacehook/whalewall#193]
Hey.

For few hours trying to understand what I'm doing wrong. I've configured like this:

```
  mariadb:
    image: mariadb:11.3.2
    container_name: mariadb
    restart: always
    ports:
      - '3306:3306'
    volumes:
      - mariadb-data:/var/lib/mysql
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro
    environment:
      - MARIADB_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MARIADB_DATABASE=mail-service
      - MARIADB_USER=mail-service
      - MARIADB_PASSWORD=${MYSQL_PASSWORD}
    labels:
      whalewall.enabled: true
      whalewall.rules: |
        mapped_ports:
          localhost:
            allow: true
          external:
            allow: true
            ips:
              - "192.168.1.0/24"
```

But once I deploy I get this error:

```
{"level":"error","time":"2024-03-21T23:19:08.073478263Z","msg":"error creating rules","container.id":"753d9138c41f","container.name":"mariadb","error":"error parsing rules: yaml: unmarshal errors:\n  line 6: field ips not found in type whalewall.externalRules","stacktrace":"github.com/capnspacehook/whalewall.(*RuleManager).createRules\n\tgithub.com/capnspacehook/whalewall/create.go:64\ngithub.com/capnspacehook/whalewall.(*RuleManager).Start.func1\n\tgithub.com/capnspacehook/whalewall/manager.go:112"}
```
