### ISSUE TITLE
Doesn't work in my nodejs app

### ISSUE THREAD

**Issue by lucius100** [capnspacehook/whalewall#219]
Usually it works in other docker apps
I have my own docker nodejs app, and somehow it doesn't work

here is my configuration

```
    labels:
      whalewall.enabled: 'true'
      whalewall.rules: |
        mapped_ports:
          localhost:
            allow: false
          external:
            allow: true
            ips:
              - "whitelist-ip"
        output:
          proto: tcp
          dst_ports:
            - 15386
```

does the only way to see log is in /var/log/kern.log ?
I want to troubleshoot feels so hard
my app connect to external redis port 15386

I still can accesss my app on my-ip:3306
my app is on port 3306
access mydomain.com also works, but access exposed port also work, instead of allow only whitelist-ip , any ip can access the app via my-ip:3306
