### ISSUE TITLE
Allow DNS Name

### ISSUE THREAD

**Issue by davidemiccone** [capnspacehook/whalewall#252]
It should be very useful to allow to use Dynamic DNS.
This means that whalewall need to accept a name instead of IP, also update intervall should be specified.

```
services:
  minio:
    container_name: Minio
    command: server /data --console-address ":9001"
    env_file:
    - minio.env
    labels:
      whalewall.enabled: true
      whalewall.rules: |
        mapped_ports:
          localhost:
            allow: true
          external:
            allow: true
            log_prefix: "minio"
            ##### This paragraph allow me to define Dynamic DNS Name
            dns:
              - myname.no-ip.com
              - refresh_interval: 5s
            #####
    image: quay.io/minio/minio:latest
    ports:
      - '9000:9000'
      - '9001:9001'
    volumes:
      - /minio/data:/data
      - /minio/certs:/root/.minio/certs
    restart: unless-stopped
```
