### ISSUE TITLE
Cannot start the container

### ISSUE THREAD

**Issue by jorgepsmatos** [capnspacehook/whalewall#40]
I tried with the docker-compose given

```
version: "3"
services:
  whalewall:
    cap_add: 
      - NET_ADMIN
    image: ghcr.io/capnspacehook/whalewall
    network_mode: host
    volumes:
      - whalewall_data:/data
      - /var/run/docker.sock:/var/run/docker.sock:ro

volumes:
  whalewall_data:
```

and using docker run

```
docker run --cap-add=NET_ADMIN --network=host -v whalewall_data:/data -v /var/run/docker.sock:/var/run/docker.sock:ro ghcr.io/capnspacehook/whalewall
```

but I get the following error right on startup

```
{"level":"error","time":"2022-12-26T23:29:27.95569091Z","msg":"error starting","error":"error creating base rules: couldn't find required Docker chain, is Docker running?","stacktrace":"main.mainRetCode\n\tgithub.com/capnspacehook/whalewall/cmd/whalewall/main.go:111\nmain.main\n\tgithub.com/capnspacehook/whalewall/cmd/whalewall/main.go:26\nruntime.main\n\truntime/proc.go:250"}
``` 

Any suggestions what might be happening?
